FROM golang:1.17.1-alpine3.14 as builder


# Install some build deps + ssh tools for the setup below.
RUN apk update && apk --no-cache add  build-base  git bash  coreutils openssh  openssl

# this command if you get source from bitbucket repos
# Create the directory where the application will reside
RUN mkdir -p /go/src/gitlab.privy.id/privypass/privypass-oauth2-core-se

RUN env GO111MODULE=on go get github.com/cortesi/modd/cmd/modd

COPY deployment/live-dev.conf /go

WORKDIR /go/src/gitlab.privy.id/privypass/privypass-oauth2-core-se

CMD ["modd","-f", "/go/live-dev.conf"]
